package com.example.binaryjson

import com.binarystore.Persistable

@Persistable(id = 2)
class TestClass(
        @JvmField val field1: String = "lseilghboeavn",
        @JvmField val field2: String = "lseilghboeavn",
        @JvmField val field3: TestClassJava = TestClassJava(
                "", false, null, 0),
        @JvmField val field4: String = "lseilghboeavn",
        @JvmField val field5: String = "lseilghboeavn",
        @JvmField val field6: String = "lseilghboeavn",
        @JvmField val field7: String = "lseilghboeavn",
        @JvmField val field8: String = "lseilghboeavn",
        @JvmField val field9: String = "lseilghboeavn",
        @JvmField val field10: String = "fjnslgrebdfvd",
        @JvmField val field11: String = "fjnslgrebdfvd",
        @JvmField val field12: String = "fjnslgrebdfvd",
        @JvmField val field13: String = "fjnslgrebdfvd",
        @JvmField val field14: String = "fjnslgrebdfvd",
        @JvmField val field15: String = "fjnslgrebdfvd",
        @JvmField val field16: String = "fjnslgrebdfvd",
        @JvmField val field17: String = "fjnslgrebdfvd",
        @JvmField val field18: String = "fjnslgrebdfvd",
        @JvmField val field19: String = "fjnslgrebdfvd",
        @JvmField val field110: String = "sdfedgdsv",
        @JvmField val field111: String = "sdfedgdsv",
        @JvmField val field112: String = "sdfedgdsv",
        @JvmField val field21: String = "sjfloafsd",
        @JvmField val field22: String = "sjfloafsd",
        @JvmField val field23: String = "sjfloafsd",
        @JvmField val field24: String = "sjfloafsd",
        @JvmField val field25: String = "sjfloafsd",
        @JvmField val field26: String = "sjfloafsd",
        @JvmField val field27: String = "sjfloafsd",
        @JvmField val field28: String = "sjfloafsd",
        @JvmField val field29: String = "sjfloafsd",
        @JvmField val field210: String = "sdjkjkbsdf",
        @JvmField val field211: String = "sdjkjkbsdf",
        @JvmField val field212: String = "sdjkjkbsdf",
        @JvmField val field213: String = "sdjkjkbsdf",
        @JvmField val field214: String = "sdjkjkbsdf",
        @JvmField val field215: String = "sdjkjkbsdf",
        @JvmField val field216: String = "sdjkjkbsdf",
        @JvmField val field217: String = "sdjkjkbsdf",
        @JvmField val field218: String = "sdjkjkbsdf",
        @JvmField val field219: String = "sdjkjkbsdf",
        @JvmField val field2110: String = "sdfjcsccaca",
        @JvmField val field2111: String = "sdfjcsccaca",
        @JvmField val field2112: String = "sdfjcsccaca"
)
